.\" Manpage for vms.
.\" Contact the authors to correct errors or typos.
.TH vms 1 "30 May 2018" "1.0" "VMS Manual"
.SH NAME
vms \- Virtual Machine Simulator of Stack Virtual VM
.SH SYNOPSIS
.B vms
[OPTION]... FILE...
.PP
.B vms
OPTION... [FILE]...
.SH DESCRIPTION
vms is an ...
.SH OPTIONS
.IP "none"
 Given "program" file is executed
.IP -d
 enable debug mode, available commands:
    run : execute program until the end;
    next 'n' : execute n steps;
    file 'f' : load file 'f' to be executed
    reload : loads files in previous loaded file location
    quit: ends execution
.IP -g
enable graphical interface
.SH SEE ALSO
For more information on the project check the written report
.SH BUGS
No known bugs
.SH AUTHORS
a79032@alunos.uminho.com / a79220@alunos.uminho.com
