/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import Business.Cliente;
import Business.Componente;
import Business.Facade;
import Business.Pacote;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class ConfiguracaoPosGuiada extends javax.swing.JFrame {

    ArrayList<Componente> componentes;
    HashMap<Pacote,ArrayList<Componente>> pacotes;
    DefaultListModel dlm=new DefaultListModel();
    DefaultListModel dlm1=new DefaultListModel();
    DefaultListModel dlm2=new DefaultListModel();
    JList jl;
    JList jl1;
    JList jl2;
    ArrayList<Componente> escolhidos;
    Boolean incompatibilidades=false;
    Boolean dependencias=false;
    int nif;
    Cliente cliente;
    String passado;
    ArrayList<Cliente> clientes;
    HashMap<Pacote,ArrayList<Componente>> pacotesEscolhidos;
    
    public ConfiguracaoPosGuiada() {
        initComponents();
    }
    
    public ConfiguracaoPosGuiada(ArrayList<Componente> componentes, HashMap<Pacote,ArrayList<Componente>> pacotes, DefaultListModel dlm1, ArrayList<Componente> escolhidos,int nif,Cliente cliente, String passado, ArrayList<Cliente> clientes) {
        initComponents();
        this.componentes=componentes;
        this.pacotes=pacotes;
        this.dlm2=dlm1;
        this.escolhidos=escolhidos;
        this.nif=nif;
        this.cliente=cliente;
        this.passado=passado;
        this.clientes=clientes;
        this.pacotesEscolhidos=new HashMap<>();
        desenharScrollable();
    }
    
    public ConfiguracaoPosGuiada(ArrayList<Componente> componentes,JList jl,JList jl1,JList jl2,DefaultListModel dlm2,ArrayList<Componente> escolhidos,int nif,Cliente cliente, String passado, ArrayList<Cliente> clientes,HashMap<Pacote,ArrayList<Componente>> pE) {
        initComponents();
        this.componentes=componentes;
        this.jl=jl;
        this.jl1=jl1;
        this.jl2=jl2;
        this.dlm2=dlm2;
        this.jScrollPane1.setViewportView(this.jl);
        this.jScrollPane2.setViewportView(this.jl1);
        this.jScrollPane3.setViewportView(this.jl2);
        this.escolhidos=escolhidos;
        this.nif=nif;
        try{
        this.pacotes=Facade.getpacotes();
        }
        catch(Exception e){}
        this.cliente=cliente;
        this.passado=passado;
        this.clientes=clientes;
        this.pacotesEscolhidos=pE;
    }
    
    public void desenharScrollable() {
        this.dlm=new DefaultListModel();
        for(Componente c : this.componentes)
            this.dlm.addElement(c.toString());
        this.jl=new JList(this.dlm);
        this.jScrollPane1.setViewportView(this.jl);
        this.dlm1=new DefaultListModel();
        for(Pacote p : this.pacotes.keySet())
            this.dlm1.addElement(p.getNome());
        this.jl1=new JList(this.dlm1);
        this.jScrollPane2.setViewportView(this.jl1);
        this.jl2=new JList(this.dlm2);
        this.jScrollPane3.setViewportView(this.jl2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Concluir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Remover");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Catálogo de componentes");

        jLabel2.setText("Pacotes");

        jLabel3.setText("Componentes selecionados");

        jButton3.setText("Adicionar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Consultar pacote");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Adicionar pacote");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(116, 116, 116))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton5)))
                        .addGap(11, 11, 11)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(100, 100, 100))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 8, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton3)
                                .addComponent(jButton4)
                                .addComponent(jButton5))
                            .addComponent(jButton1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        for(Pacote p : this.pacotes.keySet())
            if(p.getNome().equals(this.jl1.getSelectedValue())) {
                new PacoteDetalhes(p,this.pacotes.get(p),this.componentes,this.jl,this.jl1,this.jl2,this.dlm2,this.escolhidos,this.nif,this.cliente,this.passado,this.clientes,this.pacotesEscolhidos).setVisible(true);
                this.dispose();
            }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int indice1=this.jl.getSelectedIndex();
        if(!escolhidos.contains(this.componentes.get(indice1))) {
            escolhidos.add(this.componentes.get(indice1));
            this.dlm2.addElement(this.componentes.get(indice1).toString2());
            this.jl2=new JList(this.dlm2);
            this.jScrollPane3.setViewportView(this.jl2);
        }
        try {
        if (Facade.existemIncompatibilidades(this.escolhidos)){
            this.incompatibilidades=true;
            jButton1.setVisible(false);
            jButton3.setVisible(false);
            jButton4.setVisible(false);
            jButton5.setVisible(false);
            try{
            HashSet<String> incompativeis = Facade.listaIncompatibilidades(this.escolhidos);
            StringBuilder sb = new StringBuilder();
            sb.append("Os seguinte componentes estão a gerar incompatibilidades:\n");
            for(String s : incompativeis)
                sb.append(s);
            JOptionPane.showMessageDialog(null,sb.toString());
                }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e.getMessage());
            }      
        }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        boolean adicionarPacote=true;
        for(Pacote p : this.pacotes.keySet())
            if(p.getNome().equals(this.jl1.getSelectedValue()))
                for(Componente c : this.pacotes.get(p)) {
                    if(!escolhidos.contains(c)){
                    this.escolhidos.add(c);
                    this.dlm2.addElement(c.toString2());
                    }
                    else
                        adicionarPacote=false;
                }
        if(adicionarPacote)
            for(Pacote p: this.pacotes.keySet())
                if(p.getNome().equals(this.jl1.getSelectedValue()))
                    this.pacotesEscolhidos.put(p,this.pacotes.get(p));
        this.jl2=new JList(this.dlm2);
        this.jScrollPane3.setViewportView(this.jl2);
        testaInc();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int indice3=this.jl2.getSelectedIndex();
        for(Pacote p : this.pacotesEscolhidos.keySet())
            for(Componente c : this.pacotesEscolhidos.get(p))
                if(c.getNome().equals(this.escolhidos.get(indice3).getNome())){
                    this.pacotesEscolhidos.remove(p);   
                    break;
                }
        this.escolhidos.remove(indice3);
        this.dlm2.remove(indice3);
        this.jl2=new JList(this.dlm2);
        this.jScrollPane3.setViewportView(this.jl2);
            try {
        if (Facade.existemIncompatibilidades(this.escolhidos)){
            try{
            HashSet<String> incompativeis = Facade.listaIncompatibilidades(this.escolhidos);
            StringBuilder sb = new StringBuilder();
            sb.append("Os seguinte componentes estão a gerar incompatibilidades:\n");
            for(String s : incompativeis)
                sb.append(s);
            JOptionPane.showMessageDialog(null,sb.toString());
            this.incompatibilidades=true;
            this.jButton1.setVisible(false);
            this.jButton3.setVisible(false);
            this.jButton4.setVisible(false);
            this.jButton5.setVisible(false);
                }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e.getMessage());
            }      
        }
        else {
            this.incompatibilidades=false;
            this.jButton1.setVisible(true);
            this.jButton3.setVisible(true);
            this.jButton4.setVisible(true);
            this.jButton5.setVisible(true);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        testaDep();
        if(this.dependencias) return;
        if(verificarObrigatorios()) {new ConfiguracaoConcluir(this.escolhidos,this.nif,this.cliente,this.passado,this.clientes,this.pacotesEscolhidos).setVisible(true); this.dispose();}
    }//GEN-LAST:event_jButton1ActionPerformed

    public void testaInc() {
        try {
        if (Facade.existemIncompatibilidades(this.escolhidos)){
            this.incompatibilidades=true;
            jButton1.setVisible(false);
            jButton3.setVisible(false);
            jButton4.setVisible(false);
            jButton5.setVisible(false);
            try{
            HashSet<String> incompativeis = Facade.listaIncompatibilidades(this.escolhidos);
            StringBuilder sb = new StringBuilder();
            sb.append("Os seguinte componentes estão a gerar incompatibilidades:\n");
            for(String s : incompativeis)
                sb.append(s);
            JOptionPane.showMessageDialog(null,sb.toString());
                }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e.getMessage());
            }      
        }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }  
    }
    
    public void testaDep() {
        try{
            if(Facade.existemDependencias(this.escolhidos)) {
                this.dependencias=true;
                HashMap<String,HashSet<String>> dependencias=Facade.listaDependencias(this.escolhidos);
                for(String s : dependencias.keySet()){
                    StringBuilder sb = new StringBuilder();
                    for(String s1 : dependencias.get(s))
                        sb.append(s1).append(" ");
                    JOptionPane.showMessageDialog(null,"" + s +" requer: " + sb.toString());
                }
            }
            else this.dependencias=false;
        }
        catch(Exception e){}
    }
    
    public boolean verificarObrigatorios() {
        ArrayList<String> emFalta = new ArrayList<String>();
        Boolean falta=true;
        String[] ob={"chassi","pintura","jantes","pneus","motor","banco","estofo","volante","TuboDeEscape","vidro","capo"};
        for(String s : ob){
            falta=true;
            for(Componente c : this.escolhidos)
                if(c.getNome().contains(s)){
                    falta=false;
                    break;
                }
            if(falta) emFalta.add(s);
        }
        if(!emFalta.isEmpty()){
            StringBuilder sb = new StringBuilder();
            for(String s : emFalta)
                sb.append(s).append(" ");
            JOptionPane.showMessageDialog(null,"Componentes obrigatórios em falta: " +sb.toString());
            return false;
        }
        return true;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfiguracaoPosGuiada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfiguracaoPosGuiada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfiguracaoPosGuiada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfiguracaoPosGuiada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfiguracaoPosGuiada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
