//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOSAnimal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empregado
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public System.DateTime DataNascimento { get; set; }
        public int NrTelemovel { get; set; }
        public string Status { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
    }
}
