//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOSAnimal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SOSAbdEntities1 : DbContext
    {
        public SOSAbdEntities1()
            : base("name=SOSAbdEntities1")
        {
            this.Configuration.LazyLoadingEnabled = false;
            this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Utilizador> Utilizador { get; set; }
        public virtual DbSet<Animal> Animal { get; set; }
        public virtual DbSet<Adocao> Adocao { get; set; }
        public virtual DbSet<Empregado> Empregado { get; set; }
        public virtual DbSet<Sinalizacao> Sinalizacao { get; set; }
        public virtual DbSet<Visita> Visita { get; set; }
        public virtual DbSet<Imagem> Imagem { get; set; }
        public virtual DbSet<ImagemAnimal> ImagemAnimal { get; set; }
    }
}
