//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOSAnimal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sinalizacao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sinalizacao()
        {
            this.Imagem = new HashSet<Imagem>();
        }
    
        public int Id { get; set; }
        public int IdUser { get; set; }
        public System.DateTime Data { get; set; }
        public string Nota { get; set; }
        public string Status { get; set; }
        public Nullable<double> Lat { get; set; }
        public Nullable<double> Long { get; set; }
    
        public virtual Utilizador Utilizador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Imagem> Imagem { get; set; }
    }
}
